### ISSUE TITLE
Intermittent failure in SendToOwnersTestPlanSpec.groovy

### ISSUE THREAD

**Issue by msgilligan** [OmniLayer/OmniJ#229]
There is an intermittent failure in `SendToOwnersTestPlanSpec.groovy` that looks like this:

```
foundation.omni.test.rpc.sto.SendToOwnersTestPlanRawSpec.Five equal owners (amount enough only for first four owners, amount NOT divisible by number of recipients) FAILED
    Condition not satisfied:

    balance.balance.numberValue() == expectedAvailable
    |       |       |             |  |
    |       |       1.00001584    |  1.0
    |       1.00001584            false
    [balance: 1.00001584, reserved: 1.0, frozen: 0.0]
        at app//foundation.omni.test.rpc.sto.SendToOwnersTestPlanSpec.assertBalance(SendToOwnersTestPlanSpec.groovy:447)
        at foundation.omni.test.rpc.sto.SendToOwnersTestPlanSpec.#description(SendToOwnersTestPlanSpec.groovy:72)
```

This is happening on the PR #228 branch, but I do not think it is related to the changes in the PR.

**Comment by msgilligan** [comment]
Another failure:
```
foundation.omni.test.rpc.sto.SendToOwnersTestPlanSpec.Sender owns all the coins of the STO Property after issuance (tx50, tx55) but before any distributions/sends FAILED
    Condition not satisfied:

    balance.balance.numberValue() == expectedAvailable
    |       |       |             |  |
    |       |       1.00000767    |  1.0
    |       1.00000767            false
    [balance: 1.00000767, reserved: 0.0, frozen: 0.0]
        at app//foundation.omni.test.rpc.sto.SendToOwnersTestPlanSpec.assertBalance(SendToOwnersTestPlanSpec.groovy:447)
        at foundation.omni.test.rpc.sto.SendToOwnersTestPlanSpec.#description(SendToOwnersTestPlanSpec.groovy:72)
    Sender does not have sufficient MSC for STO amount + transfer fee
    ```

**Comment by msgilligan** [comment]
There are many TODOs in `OmniTestSupport.requestOmni()` that are probably relevant to this issue.

**Comment by msgilligan** [comment]
Another one:
```
STO Property ID is non-existent FAILED
    Condition not satisfied:

    omniGetBalance(actorAddress, currencyMSC).balance == startMSC
    |              |             |            |       |  |
    |              |             CurrencyID:2 |       |  2.00000000
    |              |                          |       false
    |              |                          2.00001583
    |              2NEtNuCsLtSNFuGtz7TwkNuWbHmHyLF11fT
    [balance: 2.00001583, reserved: 0.0, frozen: 0.0]
        at foundation.omni.test.rpc.sto.SendToOwnersTestPlanSpec.STO Property ID is non-existent(SendToOwnersTestPlanSpec.groovy:158)
    STO Property ID is 0 - bitcoin
```
I think that this particular failure points towards a funding-related transaction not being included in a block, because the
```
    assert omniGetBalance(actorAddress, currencyMSC).balance == startMSC
```
on line 144 is successful, but after a block is generated the check on line 158 fails.

**Comment by msgilligan** [comment]
And another:
```
    Sender owns all the coins of the STO Property after issuance (tx50, tx55) but before any distributions/sends

foundation.omni.test.rpc.sto.SendToOwnersTestPlanRawSpec.Sender owns all the coins of the STO Property after issuance (tx50, tx55) but before any distributions/sends STANDARD_ERROR
    2023-07-07 08:16:07.223 INFO    [org.consensusj.bitcoin.jsonrpc.test.RegTestFundingSource] (org.consensusj.bitcoin.jsonrpc.test.RegTestFundingSource requestBitcoin) requestBitcoin requesting 0.0101 for 2N8MoKKuE4nY5t1mMe2roamAUfDeJ8sGBQG 
    2023-07-07 08:16:07.232 INFO    [org.consensusj.bitcoin.jsonrpc.test.RegTestFundingSource] (org.consensusj.bitcoin.jsonrpc.test.RegTestFundingSource mineEnoughFunds) mineEnoughFunds: Needed: 0.0121 Returned: 667.70680984 
    2023-07-07 08:16:07.239 INFO    [org.consensusj.bitcoin.jsonrpc.test.RegTestFundingSource] (org.consensusj.bitcoin.jsonrpc.test.RegTestFundingSource requestBitcoin) Funding transaction sent: 5ae3d8c1573d53b84206bf18373bde204582998cefb1566c2cdf0b083dedac85 
    2023-07-07 08:16:07.251 INFO    [org.consensusj.bitcoin.jsonrpc.test.RegTestFundingSource] (org.consensusj.bitcoin.jsonrpc.test.RegTestFundingSource requestBitcoin) requestBitcoin requesting 0.1 for 2N8MoKKuE4nY5t1mMe2roamAUfDeJ8sGBQG 
    2023-07-07 08:16:07.302 WARNING [org.consensusj.bitcoin.jsonrpc.test.RegTestFundingSource] (org.consensusj.bitcoin.jsonrpc.test.RegTestFundingSource logMined) ⛏⛏⛏⛏⛏ Mined 1.5625 (blk#808): Available: 670.82109784 Needed: 0.102 ⛏⛏⛏⛏⛏ 
    2023-07-07 08:16:07.302 INFO    [org.consensusj.bitcoin.jsonrpc.test.RegTestFundingSource] (org.consensusj.bitcoin.jsonrpc.test.RegTestFundingSource mineEnoughFunds) mineEnoughFunds: Needed: 0.102 Returned: 670.82109784 
    2023-07-07 08:16:07.307 INFO    [org.consensusj.bitcoin.jsonrpc.test.RegTestFundingSource] (org.consensusj.bitcoin.jsonrpc.test.RegTestFundingSource requestBitcoin) Funding transaction sent: 5d52f18e0f1eb6499a55c4d0072084e4205c9738bd942dd1b9dba59e8a5df076 

foundation.omni.test.rpc.sto.SendToOwnersTestPlanRawSpec.Sender owns all the coins of the STO Property after issuance (tx50, tx55) but before any distributions/sends FAILED
    Condition not satisfied:

    balance.balance.numberValue() == expectedAvailable
    |       |       |             |  |
    |       |       1.00000792    |  1.0
    |       1.00000792            false
    [balance: 1.00000792, reserved: 0.0, frozen: 0.0]
        at app//foundation.omni.test.rpc.sto.SendToOwnersTestPlanSpec.assertBalance(SendToOwnersTestPlanSpec.groovy:447)
        at foundation.omni.test.rpc.sto.SendToOwnersTestPlanSpec.#description(SendToOwnersTestPlanSpec.groovy:95)
    Sender does not have sufficient MSC for STO amount + transfer fee
```
This one is interesting because for this test the expected Omni balance on line 75 and 95 is the same. And nothing in the transaction-under-test should change the balance. So where are the extra `OMNI` coming from?

**Comment by msgilligan** [comment]
Here's a failure with the additional logging turned on:
```
foundation.omni.test.rpc.sto.SendToOwnersTestPlanRawSpec.Three equal owners (amount NOT divisible by number of owners) STANDARD_ERROR
    2023-07-08 21:59:00.257 INFO    [org.consensusj.bitcoin.jsonrpc.test.RegTestFundingSource] (org.consensusj.bitcoin.jsonrpc.test.RegTestFundingSource requestBitcoin) requestBitcoin requesting 0.0011 for 2N4jfSrXwvDfhiKCwrgHUsPDeC65EXQivar 
    2023-07-08 21:59:00.270 INFO    [org.consensusj.bitcoin.jsonrpc.test.RegTestFundingSource] (org.consensusj.bitcoin.jsonrpc.test.RegTestFundingSource mineEnoughFunds) mineEnoughFunds: Needed: 0.0031 Returned: 908.8433274 
    2023-07-08 21:59:00.275 INFO    [org.consensusj.bitcoin.jsonrpc.test.RegTestFundingSource] (org.consensusj.bitcoin.jsonrpc.test.RegTestFundingSource requestBitcoin) Funding transaction sent: c501c4187408270ec91e3e9e81e4929aa12108307f93ffecd7c3bb9f886e5d17 
    2023-07-08 21:59:00.292 INFO    [org.consensusj.bitcoin.jsonrpc.test.RegTestFundingSource] (org.consensusj.bitcoin.jsonrpc.test.RegTestFundingSource requestBitcoin) requestBitcoin requesting 0.1 for 2N4jfSrXwvDfhiKCwrgHUsPDeC65EXQivar 
    2023-07-08 21:59:00.330 WARNING [org.consensusj.bitcoin.jsonrpc.test.RegTestFundingSource] (org.consensusj.bitcoin.jsonrpc.test.RegTestFundingSource logMined) ⛏⛏⛏⛏⛏ Mined 0.78125 (blk#921): Available: 910.4047668 Needed: 0.102 ⛏⛏⛏⛏⛏ 
    2023-07-08 21:59:00.330 INFO    [org.consensusj.bitcoin.jsonrpc.test.RegTestFundingSource] (org.consensusj.bitcoin.jsonrpc.test.RegTestFundingSource mineEnoughFunds) mineEnoughFunds: Needed: 0.102 Returned: 910.4047668 
    2023-07-08 21:59:00.334 INFO    [org.consensusj.bitcoin.jsonrpc.test.RegTestFundingSource] (org.consensusj.bitcoin.jsonrpc.test.RegTestFundingSource requestBitcoin) Funding transaction sent: 8750305ae044a466efa537c39f4c70ae1b93b3f1c9d454bd60e4ffb097b74de1 
    2023-07-08 21:59:00.347 INFO    [foundation.omni.rpc.OmniClient] (foundation.omni.rpc.OmniClient omniGetBalance) omni_getbalance result for 2N4jfSrXwvDfhiKCwrgHUsPDeC65EXQivar, CurrencyID:1: [balance: 0.1, reserved: 0.0, frozen: 0.0] 
    2023-07-08 21:59:00.348 INFO    [foundation.omni.rpc.OmniClient] (foundation.omni.rpc.OmniClient omniGetBalance) omni_getbalance result for 2N4jfSrXwvDfhiKCwrgHUsPDeC65EXQivar, CurrencyID:2: [balance: 0.1, reserved: 0.0, frozen: 0.0] 
    2023-07-08 21:59:00.348 INFO    [foundation.omni.test.OmniTestSupport] (org.codehaus.groovy.vmplugin.v8.IndyInterface fromCache) fundedAddress 2N4jfSrXwvDfhiKCwrgHUsPDeC65EXQivar has 0.00 BTC BTC, 0.10000000 OMNI, 0.10000000 TOMNI 
    2023-07-08 21:59:01.802 INFO    [foundation.omni.rpc.OmniClient] (foundation.omni.rpc.OmniClient omniGetBalance) omni_getbalance result for 2N4jfSrXwvDfhiKCwrgHUsPDeC65EXQivar, CurrencyID:2: [balance: 0.1000008, reserved: 0.0, frozen: 0.0] 

foundation.omni.test.rpc.sto.SendToOwnersTestPlanRawSpec.Three equal owners (amount NOT divisible by number of owners) FAILED
    Condition not satisfied:

    balance.balance.numberValue() == expectedAvailable
    |       |       |             |  |
    |       |       0.10000080    |  0.1
    |       0.10000080            false
    [balance: 0.1000008, reserved: 0.0, frozen: 0.0]
        at app//foundation.omni.test.rpc.sto.SendToOwnersTestPlanSpec.assertBalance(SendToOwnersTestPlanSpec.groovy:447)
        at foundation.omni.test.rpc.sto.SendToOwnersTestPlanSpec.#description(SendToOwnersTestPlanSpec.groovy:75)
    Two unequal owners (amount NOT divisible by the proportion)

```

With the additional logging we can see in the final log entry before the test failure that the server has returned the incorrect balance via `omni_getbalance`.

**Comment by dexX7** [comment]
On which Omni Core version is this running? Is this somehow related to the changes we made in Omni Core, or does it run against a "stable" release?

**Comment by msgilligan** [comment]
> On which Omni Core version is this running? Is this somehow related to the changes we made in Omni Core, or does it run against a "stable" release?

I've seen these failures with both the 0.11.0 binary and the 0.12.0.1 binary. I don't think it is related to recent changes.
